services:
  mysql-server:
    image: 'mysql'
    container_name: 'mysql-server'
    command:  --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
            - ./.docker/mysql/datadir/:/var/lib/mysql
    ports:
      - 3307:3306
      
    environment:
      MYSQL_ROOT_PASSWORD: "yourStrong(!)Password"
    networks:
      - network
networks:
  # Declare our private network.  We must declare one for the magic
  # Docker DNS to work, but otherwise its default settings are fine.
  network: {}