version: '3.5'

services:
  redis:
    container_name: redis
    image: redis:alpine
    environment:
      REDIS_HOST_PASSWORD: mypassword
      PGDATA: /data/redis
    volumes:
       - ./docker/redis:/data/redis
    ports:
      - "6379:6379"
    networks:
      - redis
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
  
networks:
  redis:
    driver: bridge

volumes:
    redis:
 